FactorajeCore.Web/Controllers/CustomerController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc.Rendering;
using FactorajeCore.Web.Models;
using FactorajeCore.Web.Models.Dtos;
using FactorajeCore.Web.Models.VM;
using FactorajeCore.Web.ServicesApi.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Reflection;
using System.Collections.Immutable;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using System.Collections.Generic;
using Microsoft.AspNetCore.Server.IIS.Core;

namespace FactorajeCore.Web.Controllers;


public class CustomerController : Controller
{
    
    private readonly ICustomerService _service;
    private readonly ICustomerIdentiService _serviceIdentificationType;
    private readonly IAgentService _serviceAgent;
    private readonly ICollectionAgentService _serviceCollectionAgent;
    private readonly ISegmentService _servicesegment;
    private readonly IMapper _mapper;

    public CustomerController(ICustomerService service
        , ICustomerIdentiService serviceIdentificationType
        , IAgentService serviceAgent
        , ICollectionAgentService serviceCollectionAgent
        , ISegmentService segmentService
        , IMapper mapper)
    {
        _service = service;
        _serviceIdentificationType = serviceIdentificationType;
        _serviceAgent = serviceAgent;
        _serviceCollectionAgent = serviceCollectionAgent;
        this._servicesegment = segmentService;
        _mapper = mapper;
    }
    public async Task<IActionResult> Index()
    {
        //var dataList = await GetAllData();
        return View();
    }


    [HttpGet]
    public IActionResult  GetAllData()
    {
        customerDetailsVM customerDetails = new();
        List<CustomerDto> list = new();
        var task =_service.GetAllAsync<APIResponse>();
        var response = task.Result;
        if ((response != null) && response.IsSuccess)
        {
            list = JsonConvert.DeserializeObject<List<CustomerDto>>(Convert.ToString(response.Result)).ToList();
        }
        var listViewData = list.Select(x => new CustomerIndexVM
        {
            code = x.Code,
            razon = x.Razon,
            email = x.Email,
            numberidentity = x.NumberCED
        }).ToList();

        //new { data = listViewData}
        return Json(new { data = listViewData });
    }

    [HttpGet]
    public async Task<IActionResult> DetailCustomer(string code)
    {
        customerDetailsVM customerDetails = new();
        var response = await _service.GetByCodeAsync<APIResponse>(code);
        if (response != null && response.IsSuccess)
        {
            CustomerDto model = JsonConvert.DeserializeObject<CustomerDto>(Convert.ToString(response.Result));
            customerDetails.EntityDetail = model;


        }
        response = await _serviceAgent.GetAllAsync<APIResponse>();
        if (response != null && response.IsSuccess)
        {
            customerDetails.EjecutivoVentaList = JsonConvert.DeserializeObject<List<AgentDto>>(Convert.ToString(response.Result)).
                Select(x => new SelectListItem
                {
                    Text = x.name,
                    Value = x.registryuid.ToString()
                });
        }
        response = await _serviceCollectionAgent.GetAllAsync<APIResponse>();
        if (response != null && response.IsSuccess)
        {
            customerDetails.EjecutivoCobroList = JsonConvert.DeserializeObject<List<CollectionAgentDto>>(Convert.ToString(response.Result)).
                Select(x => new SelectListItem
                {
                    Text = x.name,
                    Value = x.registryuid.ToString()
                });
        }

        response = await _serviceIdentificationType.GetAllAsync<APIResponse>();
        if (response != null && response.IsSuccess)
        {
            customerDetails.TipoIdentList = JsonConvert.DeserializeObject<List<CustomerIdentiDto>>(Convert.ToString(response.Result)).
                Select(x => new SelectListItem
                {
                    Text = x.description,
                    Value = x.registryid.ToString()
                });
        }

        response = await _servicesegment.GetAllAsync<APIResponse>();
        if (response != null && response.IsSuccess)
        {
            customerDetails.SegmentoList = JsonConvert.DeserializeObject<List<SegmentDto>>(Convert.ToString(response.Result)).
                Select(x => new SelectListItem
                {
                    Text = x.AssignedSegment,
                    Value = x.IdSegment.ToString()
                });
            return View(customerDetails);
        }
        return NotFound();

        //var response = await _service.GetByCodeAsync<APIResponse>(code);
        //if ((response != null) && response.IsSuccess)
        //{
        //    model = JsonConvert.DeserializeObject<CustomerDto>(Convert.ToString(response.Result));
        //}
        //return View(model);
    }

   

    [HttpGet]
    public async Task<IActionResult> CreateCustomer()
    {
        var model = new CustomerCreateVM();

        var responseList = await _serviceIdentificationType.GetAllAsync<APIResponse>();

        if (responseList != null && responseList.IsSuccess)
        {
            model.TipoIdentList = JsonConvert.DeserializeObject<List<CustomerIdentiDto>>(
                Convert.ToString(responseList.Result))
                .Select(x => new SelectListItem
                {
                    Text = x.description,
                    Value = x.registryid.ToString()
                });
        }

        responseList = await _serviceAgent.GetAllAsync<APIResponse>();
        if (responseList != null && responseList.IsSuccess)
        {
            model.EjecutivoVentaList = JsonConvert.DeserializeObject<List<AgentDto>>(
                Convert.ToString(responseList.Result))
                .Select(x => new SelectListItem
                {
                    Text = x.name,
                    Value = x.registryuid.ToString()
                });
        }

        responseList = await _serviceCollectionAgent.GetAllAsync<APIResponse>();
        if (responseList != null && responseList.IsSuccess)
        {
            model.EjecutivoCobroList = JsonConvert.DeserializeObject<List<CollectionAgentDto>>(
                Convert.ToString(responseList.Result))
                .Select(x => new SelectListItem
                {
                    Text = x.name,
                    Value = x.registryuid.ToString()
                });
            responseList = await _servicesegment.GetAllAsync<APIResponse>();
            if (responseList != null && responseList.IsSuccess)
            {
                model.SegmentoList = JsonConvert.DeserializeObject<List<SegmentDto>>(
                    Convert.ToString(responseList.Result))
                    .Select(x => new SelectListItem
                    {
                        Text = x.AssignedSegment,
                        Value = x.IdSegment.ToString()
                    });
            }
        }

        return View(model);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> CreateCustomer(CustomerCreateVM model)
    {

        if (ModelState.IsValid)
        {
            var response = await _service.CreateAsync<APIResponse>(model.EntityCreate);
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                if (response.ErrorMessages.Count > 0)
                {
                    ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                }
            }

        }
        var responseList = await _serviceIdentificationType.GetAllAsync<APIResponse>();
        if (responseList != null && responseList.IsSuccess)
        {
            model.TipoIdentList = JsonConvert.DeserializeObject<List<CustomerIdentiDto>>
                (Convert.ToString(responseList.Result)).Select(x => new SelectListItem
                {
                    Text = x.description,
                    Value = x.registryid.ToString()
                });

            responseList = await _serviceAgent.GetAllAsync<APIResponse>();
            if (responseList != null && responseList.IsSuccess)
            {
                model.EjecutivoVentaList = JsonConvert.DeserializeObject<List<AgentDto>>(
                    Convert.ToString(responseList.Result))
                    .Select(x => new SelectListItem
                    {
                        Text = x.name,
                        Value = x.registryuid.ToString()
                    });
            }
            responseList = await _serviceCollectionAgent.GetAllAsync<APIResponse>();
            if (responseList != null && responseList.IsSuccess)
            {
                model.EjecutivoCobroList = JsonConvert.DeserializeObject<List<CollectionAgentDto>>(
                    Convert.ToString(responseList.Result))
                    .Select(x => new SelectListItem
                    {
                        Text = x.name,
                        Value = x.registryuid.ToString()
                    });
            }
            responseList = await _servicesegment.GetAllAsync<APIResponse>();
            if (responseList != null && responseList.IsSuccess)
            {
                model.SegmentoList = JsonConvert.DeserializeObject<List<SegmentDto>>(
               Convert.ToString(responseList.Result))
               .Select(x => new SelectListItem
               {
                   Text = x.AssignedSegment,
                   Value = x.IdSegment.ToString()
               });
            }
        }
        return View(model);
    }


    //[HttpGet]
    //public async Task<IActionResult> Upsert(string code) 
    //{
    //    if(code == null)
    //    {
    //        var model = new CustomerCreateVM();

FactorajeCore.Web/Views/Customer/CreateCustomer.cshtml
@model FactorajeCore.Web.Models.VM.CustomerCreateVM

<form asp-action="CreateCustomer">
    <div class="container border p-3">
        <h1 class="text-primary">Crear Cliente</h1>

        <div class="row">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.Type" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-1">
                    <select asp-for="EntityCreate.Type" class="form-select" asp-items="@Model.TipoIdentList">
                        <option disabled selected>--Seleccione Tipo Identificacion--</option>
                    </select>
                    <span asp-validation-for="EntityCreate.Type" class="text-danger"></span>
                </div>
                <div class="col-2">
                    <label asp-for="EntityCreate.Code" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-1">
                    <input asp-for="EntityCreate.Code" class="form-control" />
                    <span asp-validation-for="EntityCreate.Code" class="text-danger"></span>
                </div>
            </div>

                <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.NumberRuc" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-3">
                    <input asp-for="EntityCreate.NumberRuc" class="form-control" value="000000-0000" />
                    <span asp-validation-for="EntityCreate.NumberRuc" class="text-danger"></span>
                </div>
                <div class="col-2">
                    <label asp-for="EntityCreate.NumberCED" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-3">
                    <input asp-for="EntityCreate.NumberCED" class="form-control" value="000-000000-0000X" />
                    <span asp-validation-for="EntityCreate.NumberCED" class="text-danger"></span>
                </div>
            </div>
          

            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.Razon" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-10 pb-3">
                    <input asp-for="EntityCreate.Razon" class="form-control" />
                    <span asp-validation-for="EntityCreate.Razon" class="text-danger"></span>
                </div>
            </div>          

            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.Name" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-10 pb-1">
                    <input asp-for="EntityCreate.Name" class="form-control" />
                    <span asp-validation-for="EntityCreate.Name" class="text-danger"></span>
                </div>
            </div>
            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.IdSegment" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-1">
                    <select asp-for="EntityCreate.IdSegment" class="form-select" asp-items="@Model.SegmentoList">
                        <option disabled selected>--Seleccione tipo de Sector--</option>
                    </select>
                    <span asp-validation-for="EntityCreate.IdSegment" class="text-danger"></span>                 
                </div>
                <div class="col-2">
                    <label asp-for="EntityCreate.Dateadmission" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-4 pb-1">
                   
                    <input asp-for="EntityCreate.Dateadmission" type="date" id="FechaActual"  class="form-control" />
                    <span asp-validation-for="EntityCreate.Dateadmission" class="text-danger"></span>
                </div>
            </div>
            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.Phone1" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-1">
                    <input asp-for="EntityCreate.Phone1" class="form-control" />
                    <span asp-validation-for="EntityCreate.Phone1" class="text-danger"></span>
                </div>
                <div class="col-2">
                    <label asp-for="EntityCreate.Phone2" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-1">
                    <input asp-for="EntityCreate.Phone2" class="form-control" value="0000-0000" />
                    <span asp-validation-for="EntityCreate.Phone2" class="text-danger"></span>
                </div>
            </div>

            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.Fax1" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-1">
                    <input asp-for="EntityCreate.Fax1" class="form-control" />
                    <span asp-validation-for="EntityCreate.Fax1" class="text-danger"></span>
                </div>

                <div class="col-2">
                    <label asp-for="EntityCreate.Email" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-1">
                    <input asp-for="EntityCreate.Email" class="form-control" />
                    <span asp-validation-for="EntityCreate.Email" class="text-danger"></span>
                </div>
            </div>

           
            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.IdAgent" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-3">
                    <select asp-for="EntityCreate.IdAgent" class="form-select" asp-items="@Model.EjecutivoVentaList">
                        <option disabled selected>--Seleccione Agente--</option>
                    </select>
                    <span asp-validation-for="EntityCreate.IdAgent" class="text-danger"></span>
                </div>


                <div class="col-2">
                    <label asp-for="EntityCreate.IdCollectionAgent" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-3 pb-3">
                    <select asp-for="EntityCreate.IdCollectionAgent" class="form-select" asp-items="@Model.EjecutivoCobroList">
                        <option disabled selected>--Seleccione Agente--</option>
                    </select>
                    <span asp-validation-for="EntityCreate.IdCollectionAgent" class="text-danger"></span>
                </div>
            </div>

            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.Address" class="control-label pt-2" style="font-size:20px;"></label>
                </div>
                <div class="col-10 pb-3">
                    <textarea asp-for="EntityCreate.Address" class="form-control" rows="3"></textarea>
                    <span asp-validation-for="EntityCreate.Address" class="text-danger"></span>
                </div>
            </div>


           @* <div class="col-4 offset-2">
                <input type="submit"  value="Crear" class="btn btn-success form-control " />
            </div>
            <div class="col-4 offset-1">
                <a asp-controller="Customer" asp-action="Index" class="btn-primary btn form-control"><i class="bi bi-box-arrow-left"></i>  Regresar</a>
            </div>*@

            <div class="form-group row">
                <div class="col offset-1">
                 
                        <partial name="_BotonesCrearYRegresar"></partial>
                       
                    
                </div>
            </div>
           

            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.Observations" class="control-label pt-2" style="font-size:20px;" hidden></label>
                </div>
                <div class="col-10 pb-3">
                     <input asp-for="EntityCreate.Observations" value="." class="form-control" row="5" type="text" hidden >
                   @* <textarea asp-for="EntityCreate.Observations" value="." class="form-control" rows="5" ></textarea>*@
                    <span asp-validation-for="EntityCreate.Observations" class="text-danger" hidden></span>
                </div>
            </div>

            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.PrincipalBalance" class="control-label pt-2" style="font-size:20px;" hidden></label>
                </div>
                <div class="col-4 pb-3">
                    <input asp-for="EntityCreate.PrincipalBalance" value="0.00" class="form-control" hidden/>
                    <span asp-validation-for="EntityCreate.PrincipalBalance" class="text-danger" hidden></span>
                </div>

                <div class="col-2">
                    <label asp-for="EntityCreate.CreditLimit" class="control-label pt-2" style="font-size:20px;" hidden></label>
                </div>
                <div class="col-4 pb-3">
                    <input asp-for="EntityCreate.CreditLimit" value="0.00" class="form-control" hidden/>
                    <span asp-validation-for="EntityCreate.CreditLimit" class="text-danger" hidden></span>
                </div>

                <div class="col-2">
                    <label asp-for="EntityCreate.ArrearsBalance" class="control-label pt-2" style="font-size:20px;" hidden></label>
                </div>
                <div class="col-4 pb-3">
                    <input asp-for="EntityCreate.ArrearsBalance" value="0.00" class="form-control"  hidden/>
                    <span asp-validation-for="EntityCreate.ArrearsBalance" class="text-danger" hidden></span>
                </div>
            </div>

            <div class="row p-0">
                <div class="col-2">
                    <label asp-for="EntityCreate.CurrentInterest" class="control-label pt-2" style="font-size:20px;" hidden></label>
                </div>
                <div class="col-4 pb-3">
                    <input asp-for="EntityCreate.CurrentInterest" value="0.00" class="form-control" hidden/>
                    <span asp-validation-for="EntityCreate.CurrentInterest" class="text-danger" hidden></span>
                </div>

                <div class="col-2">
                    <label asp-for="EntityCreate.MoratoriumInterest" class="control-label pt-2" style="font-size:20px;" hidden></label>
                </div>
                <div class="col-4 pb-3">
                    <input asp-for="EntityCreate.MoratoriumInterest" value="0.00" class="form-control" hidden/>
                    <span asp-validation-for="EntityCreate.MoratoriumInterest" class="text-danger" hidden></span>
                </div>
            </div>

            

            <div class="col-12 p-0">
                <label asp-for="EntityCreate.TypeCustomer" class="control-label pt-1" style="font-size:20px; " hidden></label>

                <div class="form-check form-check-inline ">
                    <input asp-for="EntityCreate.TypeCustomer" class="form-check-input offset-md-4" type="radio" name="inlineRadioOptions" id="inlineRadio1" value="1" checked, hidden>
                    <label class="form-check-label" for="inlineRadio1"hidden>Excelente</label>
                </div>
            </div>

            <div class="col-2 p-0">

                <label asp-for="EntityCreate.Active" class="control-label pt-1" style="font-size:20px;" hidden></label>

                <div class="form-check form-check-inline">
                    <input asp-for="EntityCreate.Active" class="form-check-input offset-md-4" type="radio" value="A" id="defaultCheck1" checked hidden>
                    <label class="form-check-label" for="defaultCheck1" hidden>
                        Activo
                    </label>
                </div>
                <div class="form-check form-check-inline">
                    <input asp-for="EntityCreate.Active" class="form-check-input offset-md" type="radio" value="I" id="defaultCheck2" disabled hidden>
                    <label class="form-check-label" for="defaultCheck2" hidden>
                        Inactivo
                    </label>
                </div>
            </div>

       
        </div>
    </div>

</form>


@section Scripts {
    <partial name="_ValidationScriptsPartial" />

    <script type="text/javascript">
        $(document).ready(function () {
            var fecha = new Date();
            document.getElementById("FechaActual").value = fecha.toJSON().slice(0, 10);
        });
    </script>
}

FactorajeCore.Web/Views/Customer/Index.cshtml
@*@model List<FactorajeCore.Web.Models.VM.CustomerIndexVM>*@

<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">Listado de Clientes</h1>
        </div>
        <div  class="col text-end pt-1">
            <a asp-controller="Customer" asp-action="CreateCustomer" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Crear Cliente</a>
        </div>
    </div>
    <div>
        <table id="tblList" class="table table-striped table-bordered" style="width:100%">
            <thead class="thead-dark">
                <tr class="table-info">
                    <th>Codigo</th>
                    <th>Nombre</th>
                    <th>Identificacion</th>
                    <th>Email</th>
                    <th></th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@*  <a onclick=Delete("/Customer/DeleteCustomer?code =${data}") class="btn btn-danger btn-sm text-white" style="cursor:pointer">*@
@*
@section Scripts {
    <script type="text/javascript" src="~/js/customer.js"></script>
}*@


@section scripts{
        <script>

    var dataTable;

    $(document).ready(function () {
        dataTable = $('#tblList')
            .DataTable({
                "ajax": {
                    "url": "@Url.Action("GetAllData","Customer")",
                    //"dataSrc": "",
                    "type": "GET",
                    "datatype": "json",
                },
                "columns": [
                    { "data": 'code', "width": "10%" },
                    { "data": 'razon', "width": "25%" },
                    { "data": 'numberidentity', "width": "20%" },
                    { "data": 'email', "width": "25%" },
                        {
                            "data": 'code',
                            "render": function (data) {
                                return `
                                <div class="text-center">
                                        <div row>
                                     <a href="/Customer/UpdateCustomer?code=${data}" class="btn btn-success btn-sm text-white" form-check-inline style="cursor:pointer">
                                        <i class="fas fa-edit"></i>
                                    </a>
                                    <a href="/Customer/DeleteCustomer?code=${data}" class="btn btn-danger btn-sm text-white" form-check-inline style="cursor:pointer">                                     
                                        <i class="fas fa-trash"></i>
                                    </a>
                                    <a href="/Customer/DetailCustomer?code=${data}" class="btn btn-primary btn-sm text-white" form-check-inline style="cursor:pointer">
                                            <i class="fa fa-list-alt"></i>
                                    </a>
                                      </div>
                                </div>
                                `;
                            }, "width": "20%"
                        }
                ],
                "language": {
                    "lengthMenu": "Mostrar _MENU_ Registros Por Pagina",
                    "zeroRecords": "Ningun Registro",
                    "info": "Mostrar page _PAGE_ de _PAGES_",
                    "infoEmpty": "no hay registros",
                    "infoFiltered": "(filtered from _MAX_ total registros)",
                    "search": "Buscar",
                    "paginate": {
                        "first": "Primero",
                        "last": "Último",
                        "next": "Siguiente",
                        "previous": "Anterior",
                    },
                },
                "lengthMenu": [10, 15, 20, 40, 50],
                "serverSide": false,
                "processing": true,
                "searching": false,

            });
    });



        //function Delete(Url) {
        //    swal({
        //        title: "Esta seguro que desea eliminar este cliente?",
        //        text: "Este regsitro no se podra recuperar",
        //        icon: "warning",
        //        buttons: true,
        //        dangerMode: true
        //    }).then((borrar) => {
        //        if (borrar) {
        //            $.ajax({
        //                type: "DELETE",
        //                url: Url,
        //                success: function (data) {
        //                    if (data.success) {
        //                        toastr.success(data.message);
        //                        dataTable.ajax.reload();
        //                    }
        //                    else {
        //                        toasr.error(data.message);
        //                    }
        //                }
        //            });
        //        }
        //    });
        //}
        </script>


       }   