FactorajeCore.Web/Controllers/CurrencyController.cs
using AutoMapper;
using FactorajeCore.Web.Models;
using FactorajeCore.Web.Models.Dtos;
using FactorajeCore.Web.ServicesApi.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace FactorajeCore.Web.Controllers;

public class CurrencyController : Controller
{
    private readonly ICurrencyService _service;
    private readonly IMapper _mapper;
    public CurrencyController(ICurrencyService service, IMapper mapper)
    {
        _service = service; 
        _mapper = mapper;
    }
    public async Task<IActionResult> Index()
    {
        List<CurrenciesDto> list = new();

        var response = await _service.GetAllAsync<APIResponse>();
        if ((response != null) && response.IsSuccess)
        {
            list = JsonConvert.DeserializeObject<List<CurrenciesDto>>(Convert.ToString(response.Result));
        }
        return View(list);
    }

    [HttpGet]
    public async Task<IActionResult> DetailCurrency(string code)
    {
        CurrenciesDto model = new();
        var response = await _service.GetByCodeAsync<APIResponse>(code);
        if ((response != null) && response.IsSuccess)
        {
            model = JsonConvert.DeserializeObject<CurrenciesDto>(Convert.ToString(response.Result));
        }
        return View(model);
    }

    [HttpGet]
    public async Task<IActionResult> UpdateCurrency(string code)
    {
        CurrenciesDto model = new();
        var response = await _service.GetByCodeAsync<APIResponse>(code);
        if ((response != null) && response.IsSuccess)
        {
            model = JsonConvert.DeserializeObject<CurrenciesDto>(Convert.ToString(response.Result));
            return View(_mapper.Map<CurrenciesDtoUpdate>(model));
        }
        return NotFound();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UpdateCurrency(CurrenciesDtoUpdate model)
    {
        if (ModelState.IsValid)
        {
            var response = await _service.UpdateAsync<APIResponse>(model.Code, model);
            if ((response != null) && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
        }
        return View(model);
    }


}

FactorajeCore.Web/Controllers/ExchangeRateController.cs
using AutoMapper;
using FactorajeCore.Web.Models;
using FactorajeCore.Web.Models.Dtos;
using FactorajeCore.Web.ServicesApi.IServices;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Configuration;
using System.Reflection;

namespace FactorajeCore.Web.Controllers;

public class ExchangeRateController : Controller
{
    private readonly IExchangeRateServices _services;
    private readonly IConfiguration _configuration;
    private readonly IMapper _mapper;
    public string codeCurrency;

    public ExchangeRateController(IExchangeRateServices services, IConfiguration configuration, IMapper mapper)
    {
        _services = services;
        this._configuration = configuration;
        _mapper = mapper;
    }
    public async Task<IActionResult> Index()
    {
        return View();
    }
    [HttpGet]
    public async Task<IActionResult> GetAllData()
    {
        codeCurrency = _configuration.GetValue<string>("ServiceUrls:CodeExchange");
        List<ExchangeRateDto> list = new();
        var response = await _services.GetAllAsync<APIResponse>(codeCurrency);
        if ((response != null) && response.IsSuccess)
        {
            list = JsonConvert.DeserializeObject<List<ExchangeRateDto>>(Convert.ToString(response.Result));
        }
        return Json(new { data = list });
    }

    [HttpPost]
   
    public async Task<IActionResult> CreateExchange(ExchangeRateDtoCreate dtoCreate)
    {
        if (ModelState.IsValid)
        {
            var response = await _services.CreateAsync<APIResponse>(dtoCreate);
            if (response != null && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                if (response.ErrorMessages.Count > 0)
                {
                    ModelState.AddModelError("ErrorMessages", response.ErrorMessages.FirstOrDefault());
                }
            }
        }
        return View(dtoCreate);

    }

    public async Task<IActionResult>UpdateExchange(DateTime dateTrx, string codeCurrency)
    {
        codeCurrency = _configuration.GetValue<string>("ServiceUrls:CodeExchange");
        ExchangeRateDto model = new();
        var response = await _services.GetByCodeAsync<APIResponse>(dateTrx, codeCurrency);
        if ((response != null) && response.IsSuccess)
        {
            model = JsonConvert.DeserializeObject<ExchangeRateDto>(Convert.ToString(response.Result));
            return View(_mapper.Map<CurrenciesDtoUpdate>(model));
        }
        return NotFound();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> UpdateExchange(ExchangeRateDtoUpdate model)
    {
        if (ModelState.IsValid)
        {
            var response = await _services.UpdateAsync<APIResponse>(model.currencyCode, model.dateTrx.ToString(), model);
            if ((response != null) && response.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
        }
        return View(model);
    }
}

FactorajeCore.Web/Controllers/InvoiceController.cs
using FactorajeCore.Web.Models;
using FactorajeCore.Web.Models.Dtos;
using FactorajeCore.Web.Models.VM;
using FactorajeCore.Web.ServicesApi.IServices;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.Emit;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using System.Security.Cryptography.Xml;
using System.Threading.Tasks;
using System.Xml;

namespace FactorajeCore.Web.Controllers;

public class InvoiceController : Controller
{
    private readonly ILetraDeCorteService _letraDeCorteService;
    private readonly ICustomerService _customerService;
    private readonly IInvoicesServices _invoicesServices;
   
   
    public InvoiceController(ILetraDeCorteService letraDeCorteService, IInvoicesServices invoicesServices, ICustomerService customerService)
    {
        _letraDeCorteService = letraDeCorteService;
        _customerService = customerService;
        _invoicesServices = invoicesServices;

    }
    public async Task<IActionResult> Index()
    {
        return View();
    }
    [HttpPost]
    public async Task<IActionResult> GeneraFac(DateTime fechaFin)
    {
        List<InvoicesDto> listInvoice = new();
        List<LetraCorteDto> list = new();
        var fechaFormateadaini = new DateTime(fechaFin.Year, fechaFin.Month, 01).Date;
        var fechaIni  = fechaFormateadaini.ToString("yyyy-MM-dd");

        var response = await _letraDeCorteService.GetByDateAsync<APIResponse>(fechaIni.ToString(), fechaFin.ToString("yyyy-MM-dd"));
        if ((response != null) && response.IsSuccess)
        {
            list = JsonConvert.DeserializeObject<List<LetraCorteDto>>(Convert.ToString(response.Result)).ToList();
            var resultadoSum = (from item in list
                                group item by new { item.clientecodigo, item.monedaletra, item.clientenombre, item.clienteCed, item.typeidenti, item.Email } into itemCliente
                                select new
                                {
                                    Email = itemCliente.Key.Email,
                                    typeidenti = itemCliente.Key.typeidenti,
                                    clienteCed = itemCliente.Key.clienteCed,
                                    clienteNombre = itemCliente.Key.clientenombre,
                                    currencyCode = itemCliente.Key.monedaletra,
                                    clienteCodigo = itemCliente.Key.clientecodigo,
                                    interescorrientesum = itemCliente.Sum(x => x.interescorrientedevengadocorte),
                                    interesvencidosum = itemCliente.Sum(x => x.interesvencidodevengadocorte),
                                    interespenalsum = itemCliente.Sum(x => x.interespenaldevengadocorte)
                                }).ToList();

            //Obtener facturas electronicas generadas
            int lastInternalNumber = 0;
            List<InvoicesDto> invoicesList = new();
            var invoicesExist = await _invoicesServices.GetAllDateAsync<APIResponse>(fechaFin.ToString("yyyy-MM-dd")); //GetAllByDateAsync<APIResponse>(fechaFin.ToString("yyyy-MM-dd"));
            if (invoicesExist.IsSuccess)
            {
                invoicesList = JsonConvert.DeserializeObject<List<InvoicesDto>>(Convert.ToString(invoicesExist.Result));
                if (invoicesList.Count > 0)
                {
                    lastInternalNumber = invoicesList.Max(x => x.referenceinternalnumber);
                    lastInternalNumber++;
                }
            }
            if (lastInternalNumber == 0)
            {
                lastInternalNumber = 1;
            }


            var createAt = DateTime.Now;
            string createAtString = createAt.ToString("O");
            createAtString = createAtString.Substring(0, createAtString.Length - 6);
            ViewBag.dateCreateAt = createAtString;
            foreach (var itemTotal in resultadoSum)
            {
                bool indSave = false;
                // si factura existe y no esta cargada
                var invoiceExist = invoicesList.FirstOrDefault(x => x.customercode.Trim().ToUpper() == itemTotal.clienteCodigo.Trim().ToUpper());

                if ((invoiceExist != null) && !invoiceExist.indupload)
                {
                    var deleteInvoice = await _invoicesServices.DeleteAsync<APIResponse>(invoiceExist.registryid);
                    indSave = true;
                }
                else if (invoiceExist == null)
                {
                    indSave = true;
                }

                if (indSave) {
                    var totalinteres = itemTotal.interescorrientesum + itemTotal.interesvencidosum + itemTotal.interespenalsum;


                    var invoiceObject = new InvoicesDtoCreate
                    {

                        invoiceamout = totalinteres,
                        customercode = itemTotal.clienteCodigo,
                        customername = itemTotal.clienteNombre,
                        currencycode = itemTotal.currencyCode,
                        transadate = fechaFin,
                        datajsoninvoice = string.Empty,
                        email = itemTotal.Email,
                        typeidenti = (int)itemTotal.typeidenti,
                        indupload = false,
                        referenceinternalnumber = lastInternalNumber,
                        customeridenti = itemTotal.clienteCed,
                        createdAt= createAt
                    };

                    var saveResult = await _invoicesServices.CreateAsync<APIResponse>(invoiceObject);
                     lastInternalNumber++;

                }


            }

        }
        return View();
    }

    [HttpGet]
    public async Task<IActionResult> MostrarFac(DateTime dateCreateAt)
    {
        string createAtString = dateCreateAt.ToString("O");
        createAtString = createAtString.Substring(0, createAtString.Length - 1);

        InvoiceIndexVM invoice = new();

        List<InvoicesDto> listInvoice = new();
        var task = await _invoicesServices.GetAllCreatedAtAsync<APIResponse>(createAtString);
              
        if ((task != null) && task.IsSuccess)
        {
            listInvoice = JsonConvert.DeserializeObject<List<InvoicesDto>>(Convert.ToString(task.Result)).ToList();
        }
        var listViewData = listInvoice.Select(x => new InvoiceIndexVM
        {
                indload = x.indupload,
                referenceinternalnumber = x.referenceinternalnumber,
                codigo = x.customercode,
                nombre = x.customername,
                monto = x.invoiceamout,
                numeroFac = x.invoicenumber

        }).ToList();

         return Json(new { data = listViewData });           
    }

    [HttpGet]
    public async Task<IActionResult> Refrescar(DateTime fechaFin)
    {
       
        InvoiceIndexVM invoice = new();
        List<InvoicesDto> listInvoice = new();
        var task = await _invoicesServices.GetAllDateAsync<APIResponse>(fechaFin.ToString("yyyy-MM-dd"));

        if ((task != null) && task.IsSuccess)
        {
            listInvoice = JsonConvert.DeserializeObject<List<InvoicesDto>>(Convert.ToString(task.Result)).ToList();
        }

        var listViewData = listInvoice.Select(x => new InvoiceIndexVM
        {
            indload = x.indupload,
            referenceinternalnumber = x.referenceinternalnumber,
            codigo = x.customercode,
            nombre = x.customername,
            monto = x.invoiceamout,
            numeroFac = x.invoicenumber

        }).ToList();

        return Json(new { data = listViewData });

    }
}

FactorajeCore.Web/Views/Shared/_BotonesActualizarYRegresar.cshtml
@model string

<div class="row">

    <div class="col">
        <button type="submit" class="btn btn-success form-control" asp-route-Code="@Model"> <i class="bi bi-pencil-square"></i>   Actualizar</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-primary form-control"><i class="bi bi-box-arrow-left"></i>   Regresar</a>
    </div>
</div>

FactorajeCore.Web/Views/Shared/_BotonesBorrarYRegresar.cshtml
@model string

<div class="row">

    <div class="col">
        <button type="submit" class="btn btn-success form-control" asp-route-Code="@Model"><i class="fas fa-trash"></i>  Eliminar</button>
    </div>
    <div class="col">
        <a asp-action="Index" class="btn btn-primary form-control"><i class="bi bi-box-arrow-left"></i>  Regresar</a>
    </div>
</div>

@section script{

    <script>

        function Delete(Url) {
               swal({
                   title: "Esta seguro que desea eliminar este cliente?",
                   text: "Este regsitro no se podra recuperar",
                   icon: "warning",
                   buttons: true,
                   dangerMode: true
               }).then((borrar) => {
                   if (borrar) {
                       $.ajax({
                           type: "DELETE",
                           url: Url,
                           success: function (model) {
                               if (model.success) {
                                   toastr.success(model.message);
                                   dataTable.ajax.reload();
                               }
                               else {
                                   toasr.error(model.message);
                               }
                           }
                       });
                   }
               });
           }
    </script>
}

FactorajeCore.Web/Views/Shared/_BotonesCrearYRegresar.cshtml
<div class="row">

    @*<div class="col">
        <button type="submit" class="btn btn-success form-control"><i class="fas fa-trash"></i> Crear</button>
    </div>*@

    <div class="col-4 offset-2">
        <button type="submit" class="btn btn-success form-control"><i class="bi bi-plus-square-fill"></i>  Crear</button>
    </div>
    <div class="col-4 offset-1">
        <a asp-action="Index" class="btn btn-primary form-control"><i class="bi bi-box-arrow-left"></i>  Regresar</a>
    </div>
</div>

FactorajeCore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FactorajeCore.Web</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/bootswatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FactorajeCore.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />*@
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
    @*<link rel="stylesheet" href="~/lib/toastr/toastr.css" />*@
    <link rel="stylesheet" href="~/lib/fontawesome/all.min.css"/>
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  @*  <link rel="stylesheet" href="/resources/demos/style.css">*@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FactorajeCore.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Currency" asp-action="Index">Currency</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>

                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Invoice" asp-action="Index">Invoice</a>
                        </li>

                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ExchangeRate" asp-action="Index">Exchange Rate</a>
                        </li>*@
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                       
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FactorajeCore.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    @*<script src="~/lib/toastr/toastr.min.js"></script>*@
    <link rel="stylesheet" href="~/lib/fontawesome/all.min.js" />
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>